// copied from https://github.com/maurer2/blue-harvest/blob/main/src/app/layout.tsx
import type { Metadata } from 'next';

import * as stylex from '@stylexjs/stylex';
import 'modern-normalize/modern-normalize.css';
import Link from 'next/link';

import './globals.css';
// import styles from './layout.styles';
import Providers from './providers';
import { getDataFromEndpoint } from './server-actions/getDataFromEndpoint/getDataFromEndpoint';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Grandwoof Barking',
};

const baseURL = 'https://swapi.dev/api';

const styles = stylex.create({
  navElement: {
    background: 'slate',
    color: 'white',
    fontSize: '16rem',
  },
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const rootCategories = await getDataFromEndpoint<Record<string, string>>(baseURL);
  const rootCategoriesFormatted = Object.entries(rootCategories).flatMap(([label, path]) => ({
    label,
    path,
  }));

  return (
    <html lang="en">
      <body>
        <Providers>
          {Boolean(rootCategoriesFormatted.length) && (
            <nav {...stylex.props(styles.navElement)}>
              <Link href="/" key="home">
                Home
              </Link>
              {rootCategoriesFormatted.map((category) => (
                <Link href={`/${category.label}`} key={category.label}>
                  {category.label}
                </Link>
              ))}
            </nav>
          )}
          {children}
        </Providers>
      </body>
    </html>
  );
}
